import { Link } from 'react-router-dom';
import type { AppContext } from '../../App';
import { CONFIG, MINUTE } from '@histereza/shared/config';
import { REASONS } from '@histereza/shared/reasons';
import { MapView } from '../../components/MapView';
import { NotificationList } from '../../components/NotificationList';
import { fmt } from '../../components/format';
export function OperationsPage({ctx}:{ctx:AppContext}){const {s,role,error,message,busy,orgId,courierId,businessId,bayId,csv,validation,validatedCsv,vehicleId,reason,plate,parkingId,reports,location,navigate,choose,request,c,route,stop,bay,path,publicBay,pb,nextRes,until,screen,action,table,setError,setMessage,setOrgId,setCourierId,setBusinessId,setBayId,setCsv,setValidation,setValidatedCsv,setVehicleId,setReason,setPlate,setParkingId,setReports}=ctx;return <>
    {(role==='operator'||role==='sim')&&<><div className="stats">{[{label:'Miejsca dostaw',value:s.bays.length},{label:'Potwierdzone sloty',value:s.reservations.filter(r=>r.status==='confirmed').length},{label:'Otwarte incydenty',value:s.incidents.filter(i=>i.status==='open').length},{label:'Automatyczne zmiany',value:s.changes.length}].map(x=><div className="stat" key={x.label}><small>{x.label}</small><strong>{x.value}</strong></div>)}</div>
    {role==='sim'&&<div className="panel"><h2>Zegar i dane demo</h2><p>Zegar symulacji jest jedynym źródłem czasu. Upływ czasu nie zależy od zegara komputera.</p><div className="actions"><button disabled={busy||!!s.deliveries.length} onClick={()=>request('/sim/demo')}>Przygotuj demo · 45 dostaw</button><button disabled={busy||!s.routes.length} onClick={()=>request('/sim/day')}>Rozpocznij dzień D · 07:00</button>{[1,5,15,60].map(minutes=><button key={minutes} className="secondary" disabled={busy} onClick={()=>request('/sim/tick',{minutes})}>+{minutes} min</button>)}<button className="danger" onClick={()=>{if(window.confirm('Usunąć bieżące dane demonstracyjne i rozpocząć od nowa?'))void request('/sim/reset');}}>Reset demo</button></div></div>}
    <div className="split"><div className="panel"><h2>{role==='operator'?'Zamknięcia i warunki':'Scenariusze zakłóceń'}</h2><label>Miejsce<select value={bayId} onChange={e=>setBayId(e.target.value)}>{s.bays.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Kurier<select value={courierId} onChange={e=>setCourierId(e.target.value)}>{s.couriers.map(c=><option key={c.id}>{c.id}</option>)}</select></label><div className="scenario-buttons">{s.scenarios.filter(x=>role==='sim'||['closure','restore'].includes(x.id)).map(x=><button className="secondary" key={x.id} disabled={busy} onClick={()=>request('/sim/scenario',{id:x.id,courierId,bayId})}>{x.name}</button>)}</div>{role==='sim'&&<><h3>Symulowany GPS + czujnik</h3><p>Ustaw czas na początek slotu, następnie potwierdź przyjazd na ekranie kuriera.</p><button disabled={busy} onClick={()=>request('/sim/gps',{courierId,bayId,occupied:true})}>Kurier przy miejscu · zajęte</button><button className="secondary" disabled={busy} onClick={()=>request('/sim/gps',{courierId,bayId,occupied:false})}>Kurier wyjechał · wolne</button></>}</div><div className="panel"><h2>Przestrzeń miasta</h2><MapView s={s}/></div></div>
    <div className="panel"><h2>Incydenty</h2>{s.incidents.length?s.incidents.map(i=><div className="list-row" key={i.id}><div><strong>{i.type}</strong><small>{i.bayId} · {i.status==='open'?'Otwarte':'Rozwiązane'} · bez wpływu na historię</small></div>{role==='operator'&&i.status==='open'&&<button className="secondary" onClick={()=>request('/operator/resolve',{id:i.id,resolution:'verified'})}>Potwierdź rozwiązanie</button>}</div>):<p className="empty">Brak incydentów.</p>}</div><div className="panel"><h2>Predykcje · horyzont 90 min</h2>{s.predictions.map(p=><div className="list-row" key={p.id}><span>{p.type} · {p.reservationId}</span><span>+{p.expectedMinutes} min</span></div>)}{!s.predictions.length&&<p className="empty">Brak wykrytych konfliktów w ostatnim ticku.</p>}</div>
    {role==='operator'&&<div className="panel"><div className="panel-title"><h2>Równość i użycie</h2><button disabled={busy} onClick={async()=>setReports(await request('/reports',undefined,'GET'))}>Odśwież raport</button></div>{reports&&<><p className={reports.warning?'warning':''}>{reports.message}</p><table><thead><tr><th>Firma</th><th>Zgłoszone</th><th>Przydzielone</th><th>Średnie oczekiwanie</th></tr></thead><tbody>{reports.rows.map((r:any)=><tr key={r.size}><td>{r.size==='small'?'Małe':'Duże'}</td><td>{r.requested}</td><td>{r.allocated} ({Math.round(r.rate*100)}%)</td><td>{r.meanWaitMin} min</td></tr>)}</tbody></table><h3>Licznik użycia · bez płatności w MVP</h3>{reports.usage.map((u:any)=><p key={u.orgId}>{u.name}: {u.units} jednostek</p>)}</>}</div>}
    <div className="panel"><h2>Plan dostaw</h2>{table(s.stops)}</div><div className="panel"><h2>Dziennik decyzji systemu</h2>{s.changes.slice(-15).reverse().map(x=><div className="list-row" key={x.id}><div><strong>{x.cause}</strong><small>{fmt(x.appliedAt)} · {x.routeId} · {x.forced?'wymuszona':'standardowa'} · {x.acknowledged?'potwierdzona':'oczekuje na OK'}</small></div></div>)}{!s.changes.length&&<p className="empty">Brak zmian planu.</p>}<details><summary>Pełny dziennik zdarzeń ({s.events.length})</summary>{s.events.slice(-100).reverse().map(e=><p key={e.id}>{fmt(e.ts)} · {e.type} · {e.actorId}</p>)}</details></div><NotificationList s={s} userId="operator"/></>}
</>; }
