import { useState } from 'react';
import type { Business } from '@histereza/shared/types';
import type { BusinessInput } from '@histereza/shared/catalog';
import type { AppContext } from '../../App';
import { BusinessPicker } from '../../components/BusinessPicker';
const blank = (): BusinessInput => ({ id: '', name: '', entryPoint: { lat: 50.054, lng: 19.944 }, workingHours: [{ from: '07:00', to: '18:00' }], unloadingConditions: '', unattendedDropAllowed: false, bayIds: [] });
export function BusinessesPage({ ctx }: { ctx: AppContext }) {
  const { s, orgId, request, busy } = ctx; const businesses = s.businesses.filter(b => b.orgId === orgId);
  const [form, setForm] = useState<BusinessInput>(blank); const [editing, setEditing] = useState<string>(); const [lookupVersion, setLookupVersion] = useState(0);
  const load = (b: Business) => { setEditing(b.id); setForm({ id: b.id, name: b.name, entryPoint: { ...b.entryPoint }, workingHours: b.workingHours.map(w => ({ ...w })), unloadingConditions: b.unloadingConditions, unattendedDropAllowed: b.unattendedDropAllowed, bayIds: s.links.filter(l => l.businessId === b.id).map(l => l.bayId) }); };
  const reset = () => { setEditing(undefined); setForm(blank()); setLookupVersion(v => v + 1); };
  const field = <K extends keyof BusinessInput>(key: K, value: BusinessInput[K]) => setForm(previous => ({ ...previous, [key]: value }));
  const remove = async (b: Business) => { if (window.confirm(`Usunąć biznes ${b.name} (${b.id})?`)) { const result = await request(`/companies/${encodeURIComponent(orgId)}/businesses/${encodeURIComponent(b.id)}`, undefined, 'DELETE'); if (result && editing === b.id) reset(); } };
  return <><div className="panel"><div className="panel-title"><h2>Baza biznesów</h2><button type="button" onClick={reset}>Dodaj biznes</button></div><p>Wyszukaj istniejący punkt po ID lub nazwie. Wybór uzupełnia formularz jego danymi.</p><BusinessPicker key={lookupVersion} businesses={businesses} onSelect={load} /><div className="table-wrap"><table><thead><tr><th>ID biznesu</th><th>Nazwa</th><th>Przyjmowanie dostaw</th><th>Miejsca</th><th>Akcje</th></tr></thead><tbody>{businesses.map(b => <tr key={b.id}><td>{b.id}</td><td>{b.name}</td><td>{b.workingHours.map(w => `${w.from}–${w.to}`).join(', ')}</td><td>{s.links.filter(l => l.businessId === b.id).map(l => s.bays.find(b => b.id === l.bayId)?.name).join(', ')}</td><td><div className="catalog-row-actions"><button type="button" className="secondary" onClick={() => load(b)}>Edytuj</button><button type="button" className="danger" disabled={busy} onClick={() => remove(b)}>Usuń</button></div></td></tr>)}</tbody></table>{!businesses.length && <p className="empty">Dodaj pierwszy biznes tej firmy.</p>}</div></div>
    <form className="panel catalog-form" onSubmit={async e => { e.preventDefault(); const result = await request(`/companies/${encodeURIComponent(orgId)}/businesses${editing ? `/${encodeURIComponent(editing)}` : ''}`, form, editing ? 'PUT' : 'POST'); if (result) reset(); }}><h2>{editing ? `Edytuj biznes · ${editing}` : 'Nowy biznes'}</h2><div className="catalog-fields"><label>ID biznesu<input required maxLength={100} disabled={!!editing} value={form.id} onChange={e => field('id', e.target.value)} /></label><label>Nazwa biznesu<input required maxLength={200} value={form.name} onChange={e => field('name', e.target.value)} /></label><label>Szerokość geograficzna<input required type="number" step="any" min={-90} max={90} value={form.entryPoint.lat} onChange={e => field('entryPoint', { ...form.entryPoint, lat: Number(e.target.value) })} /></label><label>Długość geograficzna<input required type="number" step="any" min={-180} max={180} value={form.entryPoint.lng} onChange={e => field('entryPoint', { ...form.entryPoint, lng: Number(e.target.value) })} /></label></div>
    <fieldset><legend>Godziny otwarcia / przyjmowania dostaw</legend>{form.workingHours.map((window, i) => <div className="catalog-window" key={i}><label>Od<input required type="time" value={window.from} onChange={e => field('workingHours', form.workingHours.map((w, index) => index === i ? { ...w, from: e.target.value } : w))} /></label><label>Do<input required type="time" value={window.to} onChange={e => field('workingHours', form.workingHours.map((w, index) => index === i ? { ...w, to: e.target.value } : w))} /></label><button type="button" className="secondary" disabled={form.workingHours.length === 1} onClick={() => field('workingHours', form.workingHours.filter((_, index) => index !== i))}>Usuń okno</button></div>)}<button type="button" className="secondary" disabled={form.workingHours.length >= 8} onClick={() => field('workingHours', [...form.workingHours, { from: '13:00', to: '14:00' }])}>Dodaj okno godzinowe</button><p className="hint">Godzina „do” wcześniejsza od „od” oznacza okno przez północ.</p></fieldset>
    <fieldset><legend>Miejsca obsługujące biznes</legend><div className="catalog-checks">{s.bays.map(b => <label key={b.id}><input type="checkbox" checked={form.bayIds.includes(b.id)} onChange={e => field('bayIds', e.target.checked ? [...form.bayIds, b.id] : form.bayIds.filter(id => id !== b.id))} />{b.name}</label>)}</div><p className="hint">Wybierz przynajmniej jedno miejsce. Odległość dojścia wylicza się z lokalizacji.</p></fieldset>
    <label>Warunki rozładunku<textarea value={form.unloadingConditions} maxLength={1000} onChange={e => field('unloadingConditions', e.target.value)} rows={3} /></label><label className="catalog-check"><input type="checkbox" checked={form.unattendedDropAllowed} onChange={e => field('unattendedDropAllowed', e.target.checked)} />Dozwolone pozostawienie towaru bez obecności odbiorcy</label><div className="actions"><button disabled={busy || !s.online || !form.bayIds.length} type="submit">{editing ? 'Zapisz biznes' : 'Dodaj biznes do bazy'}</button><button className="secondary" type="button" onClick={reset}>Wyczyść formularz</button></div></form></>;
}
