import { declarationsClosed, systemDay, shiftDay } from '@histereza/shared/deliveryDates';
import { priorityChoices, priorityIssues } from '@histereza/shared/priorities';
import { useState } from 'react';
import type { AppContext } from '../../App';
import type { DeliveryInput } from '@histereza/shared/deliveryInput';
import type { Delivery, Business } from '@histereza/shared/types';
import { BusinessPicker } from '../../components/BusinessPicker';
import { InlineBusinessFields, InlineVehicleFields, type NewBusiness, type NewVehicle } from '../../components/InlineCatalogFields';

export function DeliveryWorkspace({ ctx, selectedDate }: { ctx: AppContext; selectedDate: string }) {
  const { s, orgId, request, busy } = ctx;
  const open = !declarationsClosed(s.now, selectedDate, s.closedDeliveryDates);
  const today = systemDay(s.now);
  const blank = (): DeliveryInput => ({ externalRef: '', date: selectedDate, cargoType: 'standard', courierId: '', priority: 0 });
  const [mode, setMode] = useState<'manual' | 'csv'>('manual');
  const [draft, setDraft] = useState<DeliveryInput>(blank); const [editing, setEditing] = useState<string>();
  const [businessMode, setBusinessMode] = useState<'existing' | 'new'>('existing'); const [vehicleMode, setVehicleMode] = useState<'existing' | 'new'>('existing');
  const [lookupVersion, setLookupVersion] = useState(0);
  const blankBusiness = (): NewBusiness => ({ name: '', entryPoint: { lat: s.bays[0].lat, lng: s.bays[0].lng }, workingHours: [{ from: '07:00', to: '18:00' }], unloadingConditions: '', unattendedDropAllowed: false, bayIds: [] });
  const [newBusiness, setNewBusiness] = useState<NewBusiness>(blankBusiness);
  const m = s.models[0];
  const blankVehicle = (): NewVehicle => ({ registrationNumber: '', fuelType: 'diesel', emissionStandard: 6, productionYear: 2020, hasCooling: false, dimensionsVerified: false, model: { name: m.name ?? m.id, lengthM: m.lengthM, widthM: m.widthM, heightM: m.heightM, maxLoadKg: m.maxLoadKg, gvwKg: m.gvwKg } });
  const [newVehicle, setNewVehicle] = useState<NewVehicle>(blankVehicle);
  const [csv, setCsv] = useState(''); const [validation, setValidation] = useState<{ errors: { row: number; message: string }[]; deliveries: Delivery[]; newBusinessIds: string[]; newVehicleIds: string[] }>(); const [validatedCsv, setValidatedCsv] = useState('');
  const businesses = s.businesses.filter(b => b.orgId === orgId); const vehicles = s.vehicles.filter(v => v.orgId === orgId);
  const deliveries = s.deliveries.filter(d => d.carrierOrgId === orgId && d.date === selectedDate);
  const priorityOthers = s.deliveries.filter(d=>d.id!==editing);
  const priorityDraft = { id: editing ?? '__draft__', carrierOrgId: orgId, courierId: draft.courierId, vehicleId: vehicleMode==='new' ? newVehicle.id ?? '__new_vehicle__' : draft.vehicleId ?? '', date: draft.date, priority: draft.priority };
  const choices = priorityChoices(priorityOthers, priorityDraft);
  const priorityError = priorityIssues([...priorityOthers, priorityDraft])[0]?.message;
  const selectedBusiness = businesses.find(b => b.id === draft.businessId); const selectedVehicle = vehicles.find(v => v.id === draft.vehicleId);
  const selectBusiness = (b: Business) => setDraft(d => ({ ...d, businessId: b.id, businessName: b.name, workingHours: structuredClone(b.workingHours) }));
  const reset = () => { setDraft(blank()); setEditing(undefined); setBusinessMode('existing'); setVehicleMode('existing'); setLookupVersion(v => v + 1); setNewBusiness(blankBusiness()); setNewVehicle(blankVehicle()); };
  const edit = (d: Delivery) => { setMode('manual'); setEditing(d.id); setBusinessMode('existing'); setVehicleMode('existing'); setDraft({ externalRef: d.externalRef, date: d.date, cargoType: d.cargoType, courierId: d.courierId, priority: d.priority, businessId: d.businessId, businessName: d.businessName, vehicleId: d.vehicleId, workingHours: d.workingHours ? structuredClone(d.workingHours) : undefined }); setLookupVersion(v => v + 1); document.getElementById('delivery-entry')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); };
  const field = <K extends keyof DeliveryInput>(key: K, value: DeliveryInput[K]) => setDraft(d => ({ ...d, [key]: value }));
  const canEdit = (d: Delivery) => !declarationsClosed(s.now, d.date, s.closedDeliveryDates) && d.status === 'imported' && !s.stops.some(st => st.deliveryIds.includes(d.id)) && !s.routes.some(r => r.loadingList.includes(d.id));
  return <>
    {open && <>
    <div className="panel" id="delivery-entry"><div className="panel-title"><h2>Dodawanie dostaw</h2><button className="secondary" type="button" onClick={() => { reset(); setMode('manual'); }}>Nowa dostawa</button></div>
      <div className="delivery-methods" aria-label="Sposób dodawania dostaw"><button className={mode === 'csv' ? '' : 'secondary'} type="button" aria-pressed={mode === 'csv'} onClick={() => setMode('csv')}>Import CSV</button><button className={mode === 'manual' ? '' : 'secondary'} type="button" aria-pressed={mode === 'manual'} onClick={() => setMode('manual')}>Dodaj ręcznie</button></div>
      <p>Obie metody zapisują ten sam rekord dostawy. Nowe biznesy i pojazdy trafiają także do katalogów firmy.</p>
    </div>
    {mode === 'csv' ? <div className="panel"><h2>Import dostaw</h2><p>Podaj ID biznesu lub jego nazwę oraz ID pojazdu lub rejestrację.</p>
      <div className="actions"><a className="button secondary" href={`/api/samples/deliveries?orgId=${encodeURIComponent(orgId)}&date=${selectedDate}`}>Pobierz poprawny CSV</a><a className="button secondary" href={`/api/samples/errors?orgId=${encodeURIComponent(orgId)}&date=${selectedDate}`}>CSV z błędami</a><label className="button secondary">Wczytaj plik<input type="file" accept=".csv,text/csv" hidden onChange={async e => { const file = e.target.files?.[0]; if (file) { setCsv(await file.text()); setValidation(undefined); } }} /></label></div>
      <details><summary>Kolumny CSV i tworzenie nowych rekordów</summary><p>Wymagane: <code>externalRef,date,cargoType,courierId</code>. Cargo: standard, fresh lub cold. Priorytet: puste pole oznacza brak priorytetu, liczby od 1 tworzą grupy 1 → 2 → 3 → … bez luk. Wartości mogą się powtarzać.</p><p>Biznes: <code>businessId</code> lub <code>businessName</code>. Nowy biznes wymaga nazwy, <code>businessLat,businessLng,opens,closes,bayIds</code>. Kilka miejsc oddziel znakiem |. Opcjonalne: <code>unloadingConditions,unattendedDropAllowed</code>. ID można pominąć. Bez opens/closes istniejący biznes używa godzin z bazy; podane godziny dotyczą tej dostawy.</p><p>Pojazd: <code>vehicleId</code> lub <code>registrationNumber</code>. Nowy: rejestracja, <code>vehicleModelId</code> lub <code>vehicleModelName</code>, <code>fuelType,emissionStandard,productionYear,dimensionsVerified</code>, opcjonalnie <code>hasCooling</code>. Nowy model wymaga także <code>lengthM,widthM,heightM,maxLoadKg,gvwKg</code>. Istniejący model uzupełnia te parametry. Paliwo: diesel, petrol, electric. Wartości logiczne: true/false lub 1/0. Wymiary muszą być zweryfikowane, a cold wymaga chłodni.</p><p>Sprzeczności i niejednoznaczne nazwy blokują cały zapis. Nowe katalogi zapisują się razem z dostawami.</p></details>
      <label>Treść CSV<textarea value={csv} onChange={e => { setCsv(e.target.value); setValidation(undefined); }} placeholder="externalRef,businessId,date,cargoType,vehicleId,courierId,priority" rows={7} /></label>
      <div className="actions"><button disabled={busy || !s.online || !csv} onClick={async () => { const result = await request('/deliveries/import', { csv, orgId, commit: false }); if (result) { setValidation(result); setValidatedCsv(csv); } }}>Sprawdź wiersze</button><button disabled={busy || !s.online || !validation || !!validation.errors.length || validatedCsv !== csv} onClick={async () => { const result = await request('/deliveries/import', { csv, orgId, commit: true }); if (result) { if (result.errors.length) setValidation(result); else { setCsv(''); setValidation(undefined); } } }}>Importuj zweryfikowane dostawy</button></div>
      {validation && <div className="validation" aria-live="polite">{validation.errors.length ? validation.errors.map((e, i) => <p key={i}>Wiersz {e.row}: {e.message}</p>) : <p>✓ {validation.deliveries.length} poprawnych dostaw. Nowe biznesy: {validation.newBusinessIds.length}; nowe pojazdy: {validation.newVehicleIds.length}.</p>}</div>}
    </div> : <form className="panel catalog-form" onSubmit={async e => {
      e.preventDefault(); const input: DeliveryInput = { externalRef: draft.externalRef, date: draft.date, cargoType: draft.cargoType, courierId: draft.courierId, priority: draft.priority,
        ...(businessMode === 'new' ? { newBusiness } : { businessId: draft.businessId, businessName: selectedBusiness?.name ?? draft.businessName, workingHours: draft.workingHours }),
        ...(vehicleMode === 'new' ? { newVehicle } : { vehicleId: draft.vehicleId }) };
      const result = await request(editing ? `/deliveries/${encodeURIComponent(editing)}` : '/deliveries', { orgId, delivery: input }, editing ? 'PATCH' : 'POST'); if (result) reset();
    }}>
      <h2>{editing ? `Edytujesz dostawę: ${draft.externalRef} (${editing})` : 'Ręczne dodawanie dostawy'}</h2>{editing && <div className="delivery-edit-banner" role="status">Edytowany rekord: <strong>{editing}</strong><button className="secondary" type="button" onClick={reset}>Anuluj edycję</button></div>}
      <div className="catalog-fields"><label>Numer dostawy<input required disabled={!!editing} maxLength={100} value={draft.externalRef} onChange={e => field('externalRef', e.target.value)} /></label><label>Data dostawy<input required type="date" min={shiftDay(today, 1)} max={shiftDay(today, 3)} value={draft.date} onChange={e => field('date', e.target.value)} /></label><label>Typ cargo<select aria-label="Typ cargo" value={draft.cargoType} onChange={e => field('cargoType', e.target.value as DeliveryInput['cargoType'])}><option value="standard">Standard</option><option value="fresh">Świeży towar</option><option value="cold">Chłodzony</option></select></label><label>Priorytet<select aria-label="Priorytet" value={draft.priority} onChange={e=>field('priority',Number(e.target.value))}>{choices.map(option=><option key={option.value} value={option.value} disabled={option.disabled}>{option.value ? 'Priorytet '+option.value : 'Brak priorytetu'}{option.disabled ? ' — niedostępny: powstaje luka' : ''}</option>)}</select></label><label>Przypisany kurier<select required aria-label="Przypisany kurier" value={draft.courierId} onChange={e => field('courierId', e.target.value)}><option value="">Wybierz kuriera</option>{s.couriers.filter(c => c.orgId === orgId).map(c => <option key={c.id} value={c.id}>{c.id}</option>)}</select></label></div>
      <fieldset><legend>Biznes</legend><div className="delivery-methods"><button type="button" className={businessMode === 'existing' ? '' : 'secondary'} aria-pressed={businessMode === 'existing'} onClick={() => setBusinessMode('existing')}>Biznes z bazy</button><button type="button" className={businessMode === 'new' ? '' : 'secondary'} aria-pressed={businessMode === 'new'} onClick={() => setBusinessMode('new')}>Nowy biznes w formularzu</button></div>
        {businessMode === 'new' ? <InlineBusinessFields s={s} value={newBusiness} onChange={setNewBusiness} /> : <><BusinessPicker key={lookupVersion} businesses={businesses} onSelect={selectBusiness} /><label>Wybrany biznes<select required aria-label="Wybrany biznes" value={draft.businessId ?? ''} onChange={e => { const b = businesses.find(b => b.id === e.target.value); if (b) selectBusiness(b); else setDraft(d => ({ ...d, businessId: undefined, businessName: undefined, workingHours: undefined })); }}><option value="">Wybierz lub wyszukaj biznes</option>{businesses.map(b => <option key={b.id} value={b.id}>{b.id} · {b.name}</option>)}</select></label>{selectedBusiness && <><p>{selectedBusiness.name} · {selectedBusiness.id} · {selectedBusiness.entryPoint.lat}, {selectedBusiness.entryPoint.lng}<br />{selectedBusiness.unloadingConditions}<br />Miejsca: {s.links.filter(l => l.businessId === selectedBusiness.id).map(l => s.bays.find(b => b.id === l.bayId)?.name).join(', ')}</p>{(draft.workingHours ?? selectedBusiness.workingHours).map((w, i) => <div className="catalog-window" key={i}><label>Przyjmowanie od<input required type="time" value={w.from} onChange={e => field('workingHours', (draft.workingHours ?? selectedBusiness.workingHours).map((w, j) => j === i ? { ...w, from: e.target.value } : w))} /></label><label>Przyjmowanie do<input required type="time" value={w.to} onChange={e => field('workingHours', (draft.workingHours ?? selectedBusiness.workingHours).map((w, j) => j === i ? { ...w, to: e.target.value } : w))} /></label></div>)}</>}</>}
      </fieldset>
      <fieldset><legend>Pojazd</legend><div className="delivery-methods"><button type="button" className={vehicleMode === 'existing' ? '' : 'secondary'} aria-pressed={vehicleMode === 'existing'} onClick={() => setVehicleMode('existing')}>Pojazd z floty</button><button type="button" className={vehicleMode === 'new' ? '' : 'secondary'} aria-pressed={vehicleMode === 'new'} onClick={() => setVehicleMode('new')}>Nowy pojazd w formularzu</button></div>
        {vehicleMode === 'new' ? <InlineVehicleFields s={s} value={newVehicle} onChange={setNewVehicle} /> : <><label>Wybrany pojazd<select required aria-label="Wybrany pojazd" value={draft.vehicleId ?? ''} onChange={e => field('vehicleId', e.target.value || undefined)}><option value="">Wybierz pojazd z floty</option>{vehicles.map(v => <option key={v.id} value={v.id}>{v.id} · {v.registrationNumber} · {s.models.find(m => m.id === v.vehicleModelId)?.name ?? v.vehicleModelId}</option>)}</select></label>{selectedVehicle && <p>{s.vehicleOptions.find(v => v.id === selectedVehicle.id)?.reason ?? 'Dane techniczne pojazdu dostępne. Zgodność cargo zostanie sprawdzona przy zapisie.'}</p>}</>}
      </fieldset><p>Niższy numer oznacza wcześniejszą realizację: 1 → 2 → 3 → … . Grupy nie mogą mieć luk dla kuriera, pojazdu i daty. Wybór kolejnej grupy jest możliwy dopiero po utworzeniu poprzedniej; ten sam priorytet można nadać wielu dostawom. Dostawy bez priorytetu realizujemy po grupach numerowanych. Jedna grupa lub brak priorytetów pozwala na swobodną kolejność i załadunek. Plan zostanie zatwierdzony automatycznie o 00:00 rozpoczynającym dzień dostawy.</p>{priorityError && <p className="hint" role="alert">{priorityError}</p>}<div className="actions"><button type="submit" disabled={busy || !s.online || declarationsClosed(s.now, draft.date, s.closedDeliveryDates) || !!priorityError || businessMode === 'new' && !newBusiness.bayIds.length}>{editing ? 'Zapisz zmiany dostawy' : 'Dodaj dostawę'}</button><button type="button" className="secondary" onClick={reset}>Wyczyść formularz</button></div>
    </form>}
    </>}
    {!open && <div className="panel" role="status"><h2>Dostawy · {selectedDate}</h2><p>{selectedDate < today ? 'Dostawy historyczne są dostępne wyłącznie do podglądu.' : 'Dzisiejsza lista dostaw jest zamknięta od 00:00.'} Nie można dodawać, edytować ani usuwać dostaw na ten dzień.</p></div>}
    <div className="panel"><h2>Lista przygotowanych dostaw</h2><p>Wybrany dzień: {selectedDate} · {open ? 'Deklaracje do 00:00 rozpoczynającego ten dzień' : 'Tylko podgląd'}</p><div className="table-wrap"><table><thead><tr><th>Numer / ID</th><th>Biznes</th><th>Data / cargo</th><th>Pojazd / kurier</th><th>Priorytet</th><th>Akcje</th></tr></thead><tbody>{deliveries.map(d => <tr key={d.id} className={editing === d.id ? 'delivery-editing-row' : ''}><td><strong>{d.externalRef}</strong><small>{d.id}{editing === d.id ? ' · EDYTUJESZ' : ''}</small></td><td>{d.businessName}<small>{d.businessId}</small></td><td>{d.date}<small>{d.cargoType}</small></td><td>{s.vehicles.find(v => v.id === d.vehicleId)?.registrationNumber} ({d.vehicleId})<small>{d.courierId}</small></td><td>{d.priority || 'Brak'}</td><td><div className="catalog-row-actions"><button type="button" className="secondary" disabled={busy || !canEdit(d)} onClick={() => edit(d)}>Edytuj</button><button type="button" className="danger" title={priorityIssues(s.deliveries.filter(x=>x.id!==d.id))[0]?.message} disabled={busy || !canEdit(d) || !!priorityIssues(s.deliveries.filter(x=>x.id!==d.id)).length} onClick={async () => { if (window.confirm(`Usunąć dostawę ${d.externalRef} (${d.id})?`)) { const result = await request(`/deliveries/${encodeURIComponent(d.id)}?orgId=${encodeURIComponent(orgId)}`, undefined, 'DELETE'); if (result) { if (editing === d.id) reset(); setValidation(undefined); } } }}>Usuń</button></div>{!canEdit(d) && <small>Lista zamknięta lub dostawa w planie</small>}</td></tr>)}</tbody></table>{!deliveries.length && <p className="empty">{open ? "Dodaj ręcznie lub zaimportuj pierwsze dostawy." : "Brak dostaw na wybrany dzień."}</p>}</div></div>
  </>;
}
