import { useState } from 'react';
import type { Vehicle, VehicleModel } from '@histereza/shared/types';
import type { FleetInput } from '@histereza/shared/catalog';
import type { AppContext } from '../../App';
const asModel = (m: VehicleModel) => ({ name: m.name ?? m.id, lengthM: m.lengthM, widthM: m.widthM, heightM: m.heightM, maxLoadKg: m.maxLoadKg, gvwKg: m.gvwKg });
export function FleetPage({ ctx }: { ctx: AppContext }) {
  const { s, orgId, busy, request } = ctx;
  const blank = (): FleetInput => ({ id: '', registrationNumber: '', fuelType: 'diesel', emissionStandard: 6, productionYear: 2020, hasCooling: false, dimensionsVerified: false, model: asModel(s.models[0]) });
  const [form, setForm] = useState<FleetInput>(blank); const [editing, setEditing] = useState<string>(); const [filter, setFilter] = useState('');
  const field = <K extends keyof FleetInput>(key: K, value: FleetInput[K]) => setForm(previous => ({ ...previous, [key]: value }));
  const reset = () => { setEditing(undefined); setForm(blank()); };
  const load = (v: Vehicle) => { setEditing(v.id); setForm({ id: v.id, registrationNumber: v.registrationNumber, fuelType: v.fuelType, emissionStandard: v.emissionStandard, productionYear: v.productionYear, hasCooling: v.hasCooling, dimensionsVerified: v.dimensionsVerified, model: asModel(s.models.find(m => m.id === v.vehicleModelId)!) }); };
  const vehicles = s.vehicles.filter(v => v.orgId === orgId && `${v.id} ${v.registrationNumber} ${s.models.find(m => m.id === v.vehicleModelId)?.name ?? v.vehicleModelId}`.toLocaleLowerCase('pl').includes(filter.toLocaleLowerCase('pl')));
  const numbers: { key: 'lengthM' | 'widthM' | 'heightM' | 'maxLoadKg' | 'gvwKg'; label: string; max: number }[] = [{ key: 'lengthM', label: 'Długość (m)', max: 30 }, { key: 'widthM', label: 'Szerokość (m)', max: 5 }, { key: 'heightM', label: 'Wysokość (m)', max: 6 }, { key: 'maxLoadKg', label: 'Ładowność (kg)', max: 50000 }, { key: 'gvwKg', label: 'DMC (kg)', max: 60000 }];
  return <><div className="panel"><div className="panel-title"><h2>Flota firmy</h2><button type="button" onClick={reset}>Dodaj pojazd</button></div><label>Wyszukaj pojazd<input value={filter} onChange={e => setFilter(e.target.value)} placeholder="ID, rejestracja lub model" /></label><div className="table-wrap"><table><thead><tr><th>ID / rejestracja</th><th>Model i wymiary</th><th>SCT / przydział</th><th>Akcje</th></tr></thead><tbody>{vehicles.map(v => { const model = s.models.find(m => m.id === v.vehicleModelId)!; const option = s.vehicleOptions.find(o => o.id === v.id)!; return <tr key={v.id}><td><strong>{v.id}</strong><small>{v.registrationNumber}</small></td><td>{model.name ?? model.id}<small>{model.lengthM} × {model.widthM} × {model.heightM} m · DMC {model.gvwKg} kg</small></td><td>{option.sctStatus === 'paid' ? 'Wjazd płatny SCT' : option.sctStatus === 'forbidden' ? 'Zakaz SCT' : 'Zgodny SCT'}<small>{option.reason ?? 'Może otrzymać zgodne miejsce'}</small></td><td><div className="catalog-row-actions"><button className="secondary" type="button" onClick={() => load(v)}>Edytuj</button><button className="danger" type="button" disabled={busy} onClick={async () => { if (window.confirm(`Usunąć pojazd ${v.registrationNumber} (${v.id})?`)) { const result = await request(`/companies/${encodeURIComponent(orgId)}/fleet/${encodeURIComponent(v.id)}`, undefined, 'DELETE'); if (result && editing === v.id) reset(); } }}>Usuń</button></div></td></tr>; })}</tbody></table>{!vehicles.length && <p className="empty">Brak pojazdów spełniających wyszukiwanie.</p>}</div></div>
    <form className="panel catalog-form" onSubmit={async e => { e.preventDefault(); const result = await request(`/companies/${encodeURIComponent(orgId)}/fleet${editing ? `/${encodeURIComponent(editing)}` : ''}`, form, editing ? 'PUT' : 'POST'); if (result) reset(); }}><h2>{editing ? `Edytuj pojazd · ${editing}` : 'Nowy pojazd'}</h2><div className="catalog-fields"><label>ID pojazdu we flocie<input required disabled={!!editing} maxLength={100} value={form.id} onChange={e => field('id', e.target.value)} /></label><label>Numer rejestracyjny<input required maxLength={20} value={form.registrationNumber} onChange={e => field('registrationNumber', e.target.value.toUpperCase())} /></label><label>Wczytaj dane istniejącego modelu<select value="" onChange={e => { const model = s.models.find(m => m.id === e.target.value); if (model) field('model', asModel(model)); }}><option value="">Wybierz model lub wpisz własny</option>{s.models.map(m => <option key={m.id} value={m.id}>{m.name ?? m.id} · {m.lengthM} × {m.widthM} m</option>)}</select></label><label>Model / typ pojazdu<input required maxLength={120} value={form.model.name} onChange={e => field('model', { ...form.model, name: e.target.value })} /></label>{numbers.map(n => <label key={n.key}>{n.label}<input required type="number" step="any" min={n.key === 'maxLoadKg' ? 0 : 0.01} max={n.max} value={form.model[n.key]} onChange={e => field('model', { ...form.model, [n.key]: Number(e.target.value) })} /></label>)}<label>Paliwo<select value={form.fuelType} onChange={e => field('fuelType', e.target.value as FleetInput['fuelType'])}><option value="diesel">Diesel</option><option value="petrol">Benzyna</option><option value="electric">Elektryczny</option></select></label><label>Norma Euro<select value={form.emissionStandard} onChange={e => field('emissionStandard', Number(e.target.value))}>{Array.from({ length: 8 }, (_, i) => <option key={i} value={i}>{i === 0 ? 'Brak / nie dotyczy' : `Euro ${i}`}</option>)}</select></label><label>Rok produkcji<input required type="number" min={1900} max={2100} value={form.productionYear} onChange={e => field('productionYear', Number(e.target.value))} /></label></div><div className="catalog-checks"><label><input type="checkbox" checked={form.hasCooling} onChange={e => field('hasCooling', e.target.checked)} />Chłodnia</label><label><input type="checkbox" checked={form.dimensionsVerified} onChange={e => field('dimensionsVerified', e.target.checked)} />Wymiary zweryfikowane</label></div><p className="hint">Możesz przechowywać pojazd niezgodny z SCT lub wymiarami miejsc. Obecna walidacja nadal blokuje jego niedozwolony przydział.</p><div className="actions"><button type="submit" disabled={busy || !s.online}>{editing ? 'Zapisz pojazd' : 'Dodaj pojazd do floty'}</button><button className="secondary" type="button" onClick={reset}>Wyczyść formularz</button></div></form></>;
}
