import { useEffect, useRef, useState } from 'react';
import type { SimulationCatalog, SimulationView } from '@histereza/shared/simulation';
import { CourierRoute } from '../courier/CourierRoute';
import { routeView } from '../courier/routeView';
import { fmt, dateFmt } from '../../components/format';
import './simulation.css';
export function SimulationPage() {
  const [catalog,setCatalog]=useState<SimulationCatalog>(),[session,setSession]=useState<SimulationView>();
  const [org,setOrg]=useState('org1'),[courier,setCourier]=useState('courier1'),[mode,setMode]=useState<'scenario'|'random'>('scenario'),[scenario,setScenario]=useState('morning');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[speed,setSpeed]=useState(1),[randomSeed,setRandomSeed]=useState(1);
  const inFlight=useRef(false), live=useRef<string|undefined>(undefined), alive=useRef(true);
  async function api(path:string,body?:unknown,method=body===undefined?'GET':'POST') {
    const response=await fetch('/api/sim'+path,{method,headers:{'Content-Type':'application/json','x-role':'sim'},body:body===undefined?undefined:JSON.stringify(body)});
    const data=await response.json();if(!response.ok)throw new Error(data.error);return data;
  }
  useEffect(()=>{alive.current=true;api('/catalog').then(d=>{if(alive.current)setCatalog(d);}).catch(e=>{if(alive.current)setError(String(e));});return()=>{alive.current=false;const id=live.current;if(id)void api(`/sessions/${id}/stop`,{}).catch(()=>{});};},[]);
  async function command(name:string,minutes?:number) {
    if(!session||inFlight.current)return;inFlight.current=true;setBusy(true);setError('');
    try{const d=await api(`/sessions/${session.id}/${name}`,minutes?{minutes}:{});if(alive.current)setSession(d);}catch(e){if(alive.current)setError(String(e));}finally{inFlight.current=false;if(alive.current)setBusy(false);}
  }
  useEffect(()=>{if(!session?.running)return;const timer=setInterval(()=>void command('tick',speed),1000);return()=>clearInterval(timer);},[session?.id,session?.running,speed]);
  async function prepare(){if(inFlight.current)return;inFlight.current=true;setBusy(true);setError('');try{if(live.current)await api(`/sessions/${live.current}`,undefined,'DELETE');const d=await api('/sessions',{mode,scenarioId:scenario,orgId:org,courierId:courier,seed:randomSeed});live.current=d.id;setSession(d);}catch(e){setError(String(e));}finally{inFlight.current=false;setBusy(false);}}
  const c=session?.state.couriers.find(c=>c.id===courier),route=session?.state.routes.find(r=>r.courierId===courier&&r.date===session.state.planningDate);
  const records=session?.records.filter(r=>r.courierId===courier)??[],last=records.at(-1),view=session&&c&&route?routeView(session.state,c,route):undefined;
  const selectionDisabled=!!session;
  return <><div className="panel"><h2>Izolowana demonstracja systemu</h2><p>Symulator ma własne dane i zegar. Uruchomienie, zatrzymanie i reset dotyczą wyłącznie tej sesji.</p>{error&&<p role="alert" className="error">{error}</p>}
    <div className="catalog-fields"><label>Firma symulacji<select aria-label="Firma symulacji" disabled={selectionDisabled} value={org} onChange={e=>{setOrg(e.target.value);setCourier(catalog?.couriers.find(c=>c.orgId===e.target.value)?.id??'');}}>{catalog?.organizations.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label>Kurier symulacji<select aria-label="Kurier symulacji" disabled={selectionDisabled} value={courier} onChange={e=>setCourier(e.target.value)}>{catalog?.couriers.filter(c=>c.orgId===org).map(c=><option value={c.id} key={c.id}>{c.id}</option>)}</select></label><label>Tryb symulacji<select aria-label="Tryb symulacji" disabled={selectionDisabled} value={mode} onChange={e=>setMode(e.target.value as typeof mode)}><option value="scenario">Gotowy scenariusz z pliku</option><option value="random">Losowa symulacja</option></select></label><label>Scenariusz / dane początkowe<select aria-label="Scenariusz symulacji" disabled={selectionDisabled} value={scenario} onChange={e=>setScenario(e.target.value)}>{catalog?.scenarios.map(f=><option value={f.id} key={f.id}>{f.name}</option>)}</select></label>{mode==='random'&&<label>Ziarno losowania<input aria-label="Ziarno losowania" disabled={selectionDisabled} type="number" min={0} max={4294967295} value={randomSeed} onChange={e=>setRandomSeed(Number(e.target.value))}/></label>}</div>
    <div className="actions">{!session?<button disabled={busy||!catalog} onClick={()=>void prepare()}>Przygotuj sesję</button>:<><button disabled={busy||session.running} onClick={()=>void command('start')}>Uruchom symulację</button><button className="secondary" disabled={busy||!session.running} onClick={()=>void command('stop')}>Zatrzymaj symulację</button><button className="secondary" disabled={busy} onClick={()=>void command('reset')}>Reset symulatora</button><button className="secondary" disabled={busy} onClick={async()=>{if(live.current)await api(`/sessions/${live.current}`,undefined,'DELETE');live.current=undefined;setSession(undefined);}}>Nowa sesja</button>{[1,5,15,60].map(minutes=><button key={minutes} disabled={busy||!session.running} className="secondary" onClick={()=>void command('tick',minutes)}>+{minutes} min</button>)}<label>Tempo live<select aria-label="Tempo live" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={1}>1 min / s</option><option value={5}>5 min / s</option><option value={15}>15 min / s</option></select></label></>}</div>
  </div>{session&&c&&<><div className="panel sim-live"><h2>Sesja live · {c.id}</h2><div className="stats"><div className="stat"><small>Czas symulacji</small><strong>{dateFmt(session.state.now)} · {fmt(session.state.now)}</strong></div><div className="stat"><small>Stan sesji</small><strong>{session.running?'Uruchomiona':'Zatrzymana'} · {c.status}</strong></div><div className="stat"><small>Kolejny przyjazd</small><strong>{fmt(view?.next?.plannedArrival)}</strong></div></div><p>Ostatni potwierdzony punkt / zdarzenie: {last?`${fmt(last.ts)} — ${last.text}`:'Start sesji'}</p><p>Dalszy plan: {view?.stops.filter(st=>st.status!=='done').length??0} punktów pozostało.{c.pause&&` ${c.pause.kind==='fuel'?'Tankowanie':'Przerwa'}: ${c.pause.phase}, ${c.pause.minutes} min.`}</p></div>
    {route&&<CourierRoute s={session.state} courier={c} route={route}/>}
    <div className="panel"><h2>Zakłócenia przy punktach trasy</h2>{view?.stops.map(st=><div className="sim-stop-events" key={st.id}><h3>{st.sequence+1}. {session.state.bays.find(b=>b.id===st.bayId)?.name} · {fmt(st.plannedArrival)}</h3>{records.filter(r=>r.stopId===st.id).map(r=><p key={r.id}>{fmt(r.ts)} — {r.text}{r.reaction&&<small>{r.reaction}</small>}</p>)}{!records.some(r=>r.stopId===st.id)&&<p>Brak zakłóceń dla tego punktu.</p>}</div>)}</div>
    <div className="panel"><h2>Oś czasu i reakcje systemu</h2><ol className="sim-timeline">{records.map(r=><li key={r.id} className={`sim-event ${r.kind}`}><time>{fmt(r.ts)}</time><div><strong>{r.text}</strong>{r.reaction&&<p>{r.reaction}</p>}<small>{r.stopId??'Sesja kuriera'}</small></div></li>)}</ol>{!records.length&&<p>Brak zdarzeń. Uruchom symulację.</p>}<details><summary>Log zdarzeń kuriera</summary>{session.state.events.filter(e=>e.actorId===courier||((e.payload as {courierId?:string})?.courierId===courier)).map(e=><p key={e.id}>{fmt(e.ts)} — {e.type} · {JSON.stringify(e.payload)}</p>)}</details></div>
  </>}</>;
}
