import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { Repo } from '../server/src/db/repo';
import { openDb } from '../server/src/db/db';
import { seed } from '../server/src/db/seed';
import { createApp } from '../server/src/api/app';
// Wyłącznie baza w pamięci; nie zmienia SQLite użytkownika.
const db = openDb(':memory:'); const repo = new Repo(db, seed);
const server = createApp(repo).listen(0, '127.0.0.1');
await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
try {
  browser = await chromium.launch({ channel: 'msedge', headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => void d.accept());
  await page.goto(`${base}/dispatcher`); await page.locator(".delivery-days button").filter({ hasText: "2026-10-07" }).click();
  await expect(page.getByRole('heading', { name: 'Dodawanie dostaw', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Import CSV', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Dodaj ręcznie', exact: true })).toHaveAttribute('aria-pressed', 'true');
  await page.getByLabel('Numer dostawy', { exact: true }).fill('MANUAL');
  await page.getByLabel('Wyszukaj po ID', { exact: true }).fill('business1');
  await expect(page.getByLabel('Wybrany biznes', { exact: true })).toHaveValue('business1');
  await expect(page.getByLabel('Przyjmowanie od', { exact: true })).toHaveValue('07:00');
  await page.getByLabel('Wybrany pojazd', { exact: true }).selectOption('vehicle1');
  await page.getByLabel('Przypisany kurier', { exact: true }).selectOption('courier1');
  await page.getByRole('button', { name: 'Dodaj dostawę', exact: true }).click();
  const row = page.getByRole('row').filter({ hasText: 'org1:MANUAL' });
  await expect(row).toHaveCount(1);
  await row.getByRole('button', { name: 'Edytuj', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Edytujesz dostawę: MANUAL (org1:MANUAL)', exact: true })).toBeVisible();
  await expect(page.getByLabel('Numer dostawy', { exact: true })).toBeDisabled();
  await page.getByLabel('Wybrany biznes', { exact: true }).selectOption('business3');
  await page.getByLabel('Data dostawy', { exact: true }).fill('2026-10-08');
  await page.getByLabel('Typ cargo', { exact: true }).selectOption('cold');
  await page.getByLabel('Wybrany pojazd', { exact: true }).selectOption('vehicle2');
  await page.getByLabel('Przypisany kurier', { exact: true }).selectOption('courier2');
  await page.getByLabel('Priorytet', { exact: true }).selectOption('1');
  await page.getByRole('button', { name: 'Zapisz zmiany dostawy', exact: true }).click();
  await page.locator(".delivery-days button").filter({ hasText: "2026-10-08" }).click();
  await expect(row).toContainText('business3'); await expect(row).toContainText('2026-10-08'); await expect(row).toContainText('cold'); await expect(row).toContainText('vehicle2'); await expect(row).toContainText('courier2');
  await row.getByRole('button', { name: 'Usuń', exact: true }).click(); await expect(row).toHaveCount(0);

  await page.locator(".delivery-days button").filter({ hasText: "2026-10-07" }).click();
  await page.getByLabel('Numer dostawy', { exact: true }).fill('DYNAMIC');
  await page.getByLabel('Przypisany kurier', { exact: true }).selectOption('courier1');
  await page.getByRole('button', { name: 'Nowy biznes w formularzu', exact: true }).click();
  await page.getByLabel('Nazwa nowego biznesu', { exact: true }).fill('Biznes z formularza');
  await page.locator('.catalog-checks input[type=checkbox]').first().check();
  await page.getByRole('button', { name: 'Nowy pojazd w formularzu', exact: true }).click();
  await page.getByLabel('Numer rejestracyjny', { exact: true }).fill('KR UI99');
  await page.getByLabel('Wymiary zweryfikowane', { exact: true }).check();
  await page.getByRole('button', { name: 'Dodaj dostawę', exact: true }).click();
  const dynamicRow = page.getByRole('row').filter({ hasText: 'org1:DYNAMIC' }); await expect(dynamicRow).toHaveCount(1);
  assert.ok(repo.read().businesses.some(b => b.name === 'Biznes z formularza')); assert.ok(repo.read().vehicles.some(v => v.registrationNumber === 'KR UI99'));
  await dynamicRow.getByRole('button', { name: 'Usuń', exact: true }).click(); await expect(dynamicRow).toHaveCount(0);

  await page.getByRole('button', { name: 'Import CSV', exact: true }).click();
  const nameCsv = 'externalRef,businessName,date,cargoType,registrationNumber,courierId,priority\r\nCSV1,Lokal demonstracyjny 1,2026-10-07,standard,KR DEM1,courier1,1';
  await page.getByLabel('Treść CSV', { exact: true }).fill(nameCsv);
  await page.getByRole('button', { name: 'Sprawdź wiersze', exact: true }).click(); await expect(page.locator('.validation')).toContainText('1 poprawnych dostaw');
  assert.equal(repo.read().deliveries.length, 0);
  await page.getByRole('button', { name: 'Importuj zweryfikowane dostawy', exact: true }).click();
  const csvRow = page.getByRole('row').filter({ hasText: 'org1:CSV1' }); await expect(csvRow).toHaveCount(1);
  await csvRow.getByRole('button', { name: 'Edytuj', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Edytujesz dostawę: CSV1 (org1:CSV1)', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Anuluj edycję', exact: true }).click();
  await page.getByRole('button', { name: 'Import CSV', exact: true }).click();
  await page.getByLabel('Treść CSV', { exact: true }).fill(nameCsv.replace('CSV1', 'CSV2').replace('Lokal demonstracyjny 1', 'Nieznany biznes'));
  await page.getByRole('button', { name: 'Sprawdź wiersze', exact: true }).click(); await expect(page.locator('.validation')).toContainText('Wiersz 2:'); await expect(page.getByRole('button', { name: 'Importuj zweryfikowane dostawy', exact: true })).toBeDisabled();
  await page.getByLabel('Firma kurierska', { exact: true }).selectOption('org2'); await expect(csvRow).toHaveCount(0);
  await page.setViewportSize({ width: 390, height: 844 }); await page.getByRole('button', { name: 'Import CSV', exact: true }).click(); await expect(page.getByRole('heading', { name: 'Import dostaw', exact: true })).toBeVisible();
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'Poziome przewijanie na telefonie');
  assert.deepEqual(errors, []); assert.deepEqual(repo.read().routes, []); assert.deepEqual(repo.read().stops, []); assert.equal(repo.read().closedDeliveryDates.includes("2026-10-07"), false);
  console.log('DELIVERY ENTRY UI OK: ręczne/CSV, pełna edycja i usuwanie, nowe katalogi w formularzu, błędy wierszy, zakres firmy, telefon, brak zmian cut-off i tras.');
} finally { await browser?.close(); await new Promise<void>(resolve => server.close(() => resolve())); db.close(); }
