import { chromium, expect } from '@playwright/test';
import assert from 'node:assert/strict';
import { Repo } from '../server/src/db/repo';
import { openDb } from '../server/src/db/db';
import { seed } from '../server/src/db/seed';
import { createApp } from '../server/src/api/app';
import { at } from '../server/src/sim/clock';
import { saveDelivery } from '../server/src/services/deliveryService';
const db = openDb(':memory:');
const repo = new Repo(db, () => { const s = seed(); s.now = at('2026-10-09', '23:59'); return s; });
repo.mutate(s => { for (const date of ['2026-10-10', '2026-10-11']) saveDelivery(s, 'org1', { externalRef: date, date, businessId: 'business1', vehicleId: 'vehicle1', courierId: 'courier1', cargoType: 'standard', priority: 0 }); });
const server = createApp(repo).listen(0, '127.0.0.1');
await new Promise<void>(resolve => server.once('listening', resolve));
const base = `http://127.0.0.1:${(server.address() as { port: number }).port}`;
const browser = await chromium.launch({ channel: 'msedge', headless: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } });
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${base}/dispatcher`);
  const days = page.locator('.delivery-days button');
  await expect(days).toHaveCount(6);
  for (const date of ['2026-10-07','2026-10-08','2026-10-09','2026-10-10','2026-10-11','2026-10-12']) await expect(days.filter({ hasText: date })).toHaveCount(1);
  await expect(page.getByRole('heading', { name: 'Dodawanie dostaw', exact: true })).toHaveCount(0);
  await expect(page.getByRole('button', { name: /Uruchom.*cut/i })).toHaveCount(0);
  await days.filter({ hasText: '2026-10-10' }).click();
  await expect(page.getByRole('heading', { name: 'Dodawanie dostaw', exact: true })).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: 'org1:2026-10-10' }).getByRole('button', { name: 'Edytuj', exact: true })).toBeEnabled();
  assert.equal(repo.read().routes.length, 0);
  const tick = await page.request.post(`${base}/api/operator/tick`, { headers: { 'x-role': 'operator' }, data: { minutes: 1 } }); assert.equal(tick.status(), 200);
  await expect(page.getByRole('heading', { name: 'Dodawanie dostaw', exact: true })).toHaveCount(0);
  await expect(days.filter({ hasText: '2026-10-13' })).toHaveCount(1);
  const row = page.getByRole('row').filter({ hasText: 'org1:2026-10-10' });
  await expect(row.getByRole('button', { name: 'Edytuj', exact: true })).toBeDisabled();
  await expect(row.getByRole('button', { name: 'Usuń', exact: true })).toBeDisabled();
  assert.deepEqual(repo.read().routes.map(r => r.date), ['2026-10-10']);
  await days.filter({ hasText: '2026-10-11' }).click();
  await page.getByRole('button', { name: 'Import CSV', exact: true }).click();
  await page.getByLabel('Treść CSV', { exact: true }).fill('externalRef,date,cargoType,courierId,vehicleId,businessId,priority\r\nLATE,2026-10-10,standard,courier1,vehicle1,business1,0');
  await page.getByRole('button', { name: 'Sprawdź wiersze', exact: true }).click();
  await expect(page.locator('.validation')).toContainText('Termin deklaracji dostaw na dzień 2026-10-10 już minął');
  await expect(page.getByRole('button', { name: 'Importuj zweryfikowane dostawy', exact: true })).toBeDisabled();
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  assert.deepEqual(errors, []);
  console.log('DATES UI OK: six days, midnight transition, read-only closed day, CSV deadline, future declarations without routes, mobile.');
} finally { await browser.close(); server.closeAllConnections(); await new Promise<void>(resolve => server.close(() => resolve())); db.close(); }
