export const CONFIG = {
  BUFFER_MIN: 5, NO_SHOW_TOL_MIN: 5, HORIZON_MIN: 90, HYSTERESIS_MIN: 3,
  MAX_CHANGES_PER_HOUR: 2, PLANNING_DAYS: 3, CUTOFF: '00:00', EXTERNAL_MAX_MIN: 15,
  OFFHOURS_CLEAR_MIN: 30, TARGET_UTILIZATION: 0.7, SERVICE_PERCENTILE: 80,
  MIN_OVERRIDE_PERCENTILE: 50, SCT_TRANSITION_END: '2028-12-31',
} as const;
export const MINUTE = 60_000;
