import { Link } from 'react-router-dom';
import type { AppContext } from '../../App';
import { CONFIG, MINUTE } from '@histereza/shared/config';
import { REASONS } from '@histereza/shared/reasons';
import { MapView } from '../../components/MapView';
import { NotificationList } from '../../components/NotificationList';
import { fmt } from '../../components/format';
export function PublicPage({ctx}:{ctx:AppContext}){const {s,role,error,message,busy,orgId,courierId,businessId,bayId,csv,validation,validatedCsv,vehicleId,reason,plate,parkingId,reports,location,navigate,choose,request,c,route,stop,bay,path,publicBay,pb,nextRes,until,screen,action,table,setError,setMessage,setOrgId,setCourierId,setBusinessId,setBayId,setCsv,setValidation,setValidatedCsv,setVehicleId,setReason,setPlate,setParkingId,setReports}=ctx;return <>
    {(role==='public'||path.startsWith('/bay/'))&&<div className="panel public-panel"><select value={publicBay} onChange={e=>{setBayId(e.target.value);navigate(`${path.startsWith('/bay/')?'/bay':'/qr'}/${e.target.value}`);}}>{s.bays.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><h2>{pb?.name}</h2><div className={`bay-display ${s.sensors.find(x=>x.bayId===publicBay)?.occupied?'occupied':''}`}><span>{({free:'WOLNE',occupied:'ZAJĘTE',unknown:'BRAK ODCZYTU',unavailable:'NIEDOSTĘPNE',reserved:'ZAREZERWOWANE'} as Record<string,string>)[screen?.status??'unknown']}</span><strong>{screen?.until?`do ${fmt(screen.until)}`:'Sprawdź dostępność później'}</strong></div><p>Najbliższa dostawa: {fmt(nextRes?.start)}. Postój QR ma niższe pierwszeństwo; maksymalnie 15 min i zawsze z buforem.</p>{path.startsWith('/bay/')?<><img className="qr" src={`/api/public/${publicBay}/qr`} alt="Kod QR do strony postoju"/><Link className="button" to={`/qr/${publicBay}`}>Otwórz stronę QR</Link></>:<><p>Dostępny czas: {Math.max(0,Math.floor((until-s.now)/MINUTE))} min (dodatkowo obowiązują okna strefy).</p><label>Numer rejestracyjny<input value={plate} onChange={e=>setPlate(e.target.value.toUpperCase())} maxLength={14} placeholder="KR 12345"/></label><button disabled={busy||!plate||until<=s.now} onClick={async()=>{const e=await request(`/public/${publicBay}/park`,{registrationNumber:plate});if(e){setParkingId(e.id);sessionStorage.setItem('parkingId',e.id);setMessage(`Możesz stać do ${fmt(e.allowedUntil)}.`);}}}>Rozpocznij krótki postój</button>{parkingId&&<button className="secondary" onClick={async()=>{if(await request(`/public/${publicBay}/leave`,{externalParkingId:parkingId})){setParkingId('');sessionStorage.removeItem('parkingId');}}}>Zakończ postój</button>}</>}</div>}

</>; }
