import { CourierProblems } from './CourierProblems';
import type { AppContext } from '../../App';
import { statusNames } from '../../App';
import { MINUTE } from '@histereza/shared/config';
import { REASONS } from '@histereza/shared/reasons';
import { CourierRoute, UnloadingTimer } from './CourierRoute';
import { routeView } from './routeView';
import { NotificationList } from '../../components/NotificationList';
import { fmt } from '../../components/format';
export function CourierPage({ctx}:{ctx:AppContext}){const {s,role,busy,courierId,vehicleId,reason,c,route,stop,bay,action,setCourierId,setVehicleId,setReason}=ctx;return <>
    {role==='courier'&&<div className="courier-layout"><div className="panel courier-panel"><div className="panel-title"><h2>Twoja trasa</h2><select aria-label="Kurier firmowy" disabled={c?.status==='driving'} value={courierId} onChange={e=>{setCourierId(e.target.value);setVehicleId('');}}>{s.couriers.map(c=><option key={c.id}>{c.id}</option>)}</select></div>{!route?<p className="empty">Brak trasy na dziś. Plan pojawi się automatycznie po zamknięciu deklaracji o 00:00.</p>:<><span className={`badge ${c.status}`}>{statusNames[c.status]}</span>{c.status==='idle'?<><h2>Przygotuj wyjazd</h2><label>Pojazd<select value={route.vehicleId} onChange={e=>setVehicleId(e.target.value)}>{s.vehicleOptions.filter(v=>v.orgId===c.orgId&&v.id===route.vehicleId).map(v=><option key={v.id} value={v.id} disabled={!!v.reason}>{v.registrationNumber}{v.reason?` — ${v.reason}`:v.sctStatus==='paid'?' — wjazd płatny SCT':''}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>action('vehicle',{vehicleId:route.vehicleId})}>Potwierdź pojazd</button><details><summary>Lista załadunku</summary><ol>{route.loadingList.map(id=><li key={id}>{s.deliveries.find(d=>d.id===id)?.externalRef}</li>)}</ol></details><button className="big" disabled={busy} onClick={()=>action(c.loaded?'depart':'load')}>{c.loaded?'Wyjeżdżam →':'Potwierdzam załadunek'}</button></>:c.status==='finished'?<><h2>Trasa zakończona</h2><p>Wszystkie dostawy zostały obsłużone.</p></>:<><span className="eyebrow">{stop?.frozen?'CEL ZAMROŻONY':'SYSTEM WYBRAŁ NASTĘPNY CEL'}</span><h2 className="destination">{bay?.name??'Oczekiwanie na legalny slot'}</h2><p>{stop?.deliveryIds.map(id=>s.businesses.find(b=>b.id===s.deliveries.find(d=>d.id===id)?.businessId)?.name).join(' · ')}</p><div className="slot-card"><div><small>Przyjazd</small><strong>{fmt(stop?.plannedArrival)}</strong></div><div><small>Rozładunek</small><strong>{stop?.plannedServiceMin??'—'} min</strong></div></div>{c.status==='servicing'&&<UnloadingTimer seconds={routeView(s,c,route).remainingSeconds ?? 0} />}
    <button className="big" disabled={busy||!stop||(c.status==='gate'&&(s.now<c.readyAt||s.now<(stop.plannedArrival-20*MINUTE)))} onClick={()=>action(c.status==='gate'?'drive':c.status==='driving'?'arrive':stop?.deliveryIds.some(id=>!['delivered','closed'].includes(s.deliveries.find(d=>d.id===id)!.status))?'deliver':'leave')}>{c.status==='gate'?'Jadę →':c.status==='driving'?'Jestem na miejscu':stop?.deliveryIds.some(id=>!['delivered','closed'].includes(s.deliveries.find(d=>d.id===id)!.status))?'Potwierdzam doręczenia':'Wyjeżdżam z miejsca →'}</button>
    {c.status==='gate'&&<details><summary>Nie mogę wykonać zmiany</summary><select value={reason} onChange={e=>setReason(e.target.value)}>{Object.entries(REASONS).filter(([id])=>id!=='break').map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><button disabled={busy} onClick={()=>action('cannot',{reason})}>Przekaż ograniczenie</button><button className="secondary" onClick={()=>action('ack')}>OK, przyjmuję zmianę</button></details>}{c.status==='servicing'&&<button className="secondary" disabled={busy} onClick={()=>action('closed')}>Lokal zamknięty · potwierdź GPS</button>}{c.status==='driving'&&<p className="hint">Zatrzymaj się przed potwierdzeniem. GPS i czujnik są symulowane w panelu symulatora.</p>}</>}
    <CourierProblems key={courierId} ctx={ctx}/><NotificationList s={s} userId={c.userId}/></>}</div>{route && <CourierRoute s={s} courier={c} route={route} />}</div>}

</>; }
