import { Link } from 'react-router-dom';
import type { AppContext } from '../../App';
import { statusNames } from '../../App';
import { CONFIG, MINUTE } from '@histereza/shared/config';
import { REASONS } from '@histereza/shared/reasons';
import { MapView } from '../../components/MapView';
import { NotificationList } from '../../components/NotificationList';
import { fmt } from '../../components/format';
export function CourierPage({ctx}:{ctx:AppContext}){const {s,role,error,message,busy,orgId,courierId,businessId,bayId,csv,validation,validatedCsv,vehicleId,reason,plate,parkingId,reports,location,navigate,choose,request,c,route,stop,bay,path,publicBay,pb,nextRes,until,screen,action,table,setError,setMessage,setOrgId,setCourierId,setBusinessId,setBayId,setCsv,setValidation,setValidatedCsv,setVehicleId,setReason,setPlate,setParkingId,setReports}=ctx;return <>
    {(role==='courier'||role==='independent'&&path.includes('next'))&&<div className="courier-layout"><div className="panel courier-panel"><div className="panel-title"><h2>Twoja trasa</h2><select disabled={c?.status==='driving'} value={courierId} onChange={e=>{setCourierId(e.target.value);setVehicleId('');}}>{s.couriers.filter(x=>role==='independent'?['org3','org4'].includes(x.orgId):['org1','org2'].includes(x.orgId)).map(c=><option key={c.id}>{c.id}</option>)}</select></div>{!route?<p className="empty">Brak planu tego kuriera. Użyj importu i cut-off albo przygotuj demo w symulatorze.</p>:<><span className={`badge ${c.status}`}>{statusNames[c.status]}</span>{c.status==='idle'?<><h2>Przygotuj wyjazd</h2><label>Pojazd<select value={vehicleId||c.vehicleId||''} onChange={e=>setVehicleId(e.target.value)}>{s.vehicleOptions.filter(v=>v.orgId===c.orgId).map(v=><option key={v.id} value={v.id} disabled={!!v.reason}>{v.registrationNumber}{v.reason?` — ${v.reason}`:v.sctStatus==='paid'?' — wjazd płatny SCT':''}</option>)}</select></label><button className="secondary" disabled={busy} onClick={()=>action('vehicle',{vehicleId:vehicleId||c.vehicleId})}>Potwierdź pojazd</button><details><summary>Lista załadunku</summary><ol>{route.loadingList.map(id=><li key={id}>{s.deliveries.find(d=>d.id===id)?.externalRef}</li>)}</ol></details><button className="big" disabled={busy} onClick={()=>action(c.loaded?'depart':'load')}>{c.loaded?'Wyjeżdżam →':'Potwierdzam załadunek'}</button></>:c.status==='finished'?<><h2>Trasa zakończona</h2><p>Wszystkie dostawy zostały obsłużone.</p></>:<><span className="eyebrow">{stop?.frozen?'CEL ZAMROŻONY':'SYSTEM WYBRAŁ NASTĘPNY CEL'}</span><h2 className="destination">{bay?.name??'Oczekiwanie na legalny slot'}</h2><p>{stop?.deliveryIds.map(id=>s.businesses.find(b=>b.id===s.deliveries.find(d=>d.id===id)?.businessId)?.name).join(' · ')}</p><div className="slot-card"><div><small>Przyjazd</small><strong>{fmt(stop?.plannedArrival)}</strong></div><div><small>Rozładunek</small><strong>{stop?.plannedServiceMin??'—'} min</strong></div></div>{c.status==='servicing'&&<p className="timer">Czas postoju: {Math.max(0,Math.floor((s.now-(stop?.actualArrival??s.now))/MINUTE))} min</p>}
    <button className="big" disabled={busy||!stop||(c.status==='gate'&&(s.now<c.readyAt||s.now<(stop.plannedArrival-20*MINUTE)))} onClick={()=>action(c.status==='gate'?'drive':c.status==='driving'?'arrive':stop?.deliveryIds.some(id=>!['delivered','closed'].includes(s.deliveries.find(d=>d.id===id)!.status))?'deliver':'leave')}>{c.status==='gate'?'Jadę →':c.status==='driving'?'Jestem na miejscu':stop?.deliveryIds.some(id=>!['delivered','closed'].includes(s.deliveries.find(d=>d.id===id)!.status))?'Potwierdzam doręczenia':'Wyjeżdżam z miejsca →'}</button>
    {c.status==='gate'&&<details><summary>Nie mogę wykonać zmiany</summary><select value={reason} onChange={e=>setReason(e.target.value)}>{Object.entries(REASONS).map(([id,label])=><option value={id} key={id}>{label}</option>)}</select><button disabled={busy} onClick={()=>action('cannot',{reason})}>Przekaż ograniczenie</button><button className="secondary" onClick={()=>action('ack')}>OK, przyjmuję zmianę</button></details>}{c.status==='servicing'&&<button className="secondary" disabled={busy} onClick={()=>action('closed')}>Lokal zamknięty · potwierdź GPS</button>}{c.status==='driving'&&<p className="hint">Zatrzymaj się przed potwierdzeniem. GPS i czujnik są symulowane w panelu symulatora.</p>}</>}
    <NotificationList s={s} userId={c.userId}/></>}</div><div className="panel"><h2>Podgląd trasy</h2><MapView s={s}/>{c.status!=='driving'&&table(s.stops.filter(st=>st.routeId===route?.id))}</div></div>}

</>; }
